stages:
  - build
  - deploy

variables:
  GIT_SSL_NO_VERIFY: 1
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: code.chs.usgs.gov:5001/asc/stac_browser_deploy
  only:
    - v3
  script:
    - npm install
    - npm run build -- --pathPrefix="/browser-dev/" --catalogUrl="https://asc-stacbrowser.s3.us-west-2.amazonaws.com/catalog.json"
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  image: usgsastro/aws-cli:latest
  only:
    - v3
  dependencies: 
    - build
  script:
    - aws s3 sync --delete dist s3://asc-stacbrowser/browser-dev/


