module.exports = {
    catalogUrl: "https://6vpdmaqce6.execute-api.us-west-2.amazonaws.com/",
    catalogTitle: "USGS Astrogeology Planetary ARD",
    allowExternalAccess: false, // Must be true if catalogUrl is not given
    allowedDomains: [],
    detectLocaleFromBrowser: true,
    storeLocale: true,
    locale: "en",
    fallbackLocale: "en",
    supportedLocales: [
        "de",
//      "de-CH",
        "es",
        "en",
        "fr",
//      "fr-CA",
//      "fr-CH",
        "it",
//      "it-CH",
        "ro"
    ],
    apiCatalogPriority: null,
    useTileLayerAsFallback: true,
    tileSourceTemplate: null,
    displayGeoTiffByDefault: false,
    buildTileUrlTemplate: ({href, asset}) => "https://tiles.rdnt.io/tiles/{z}/{x}/{y}@2x?url=" + encodeURIComponent(asset.href.startsWith("/vsi") ? asset.href : href),
    stacProxyUrl: null,
    pathPrefix: "/browse-dev",
    historyMode: "history",
    cardViewMode: 'cards',
    showThumbnailsAsAssets: false,
    stacLint: true,
    geoTiffResolution: 512,
    redirectLegacyUrls: false,
    itemsPerPage: 24,
    crossOriginMedia: null,
    defaultThumbnailSize: null,
    maxPreviewsOnMap: 50,
    requestHeaders: {},
    requestQueryParameters: {},
    preprocessSTAC: null,
    authConfig: null
};
